---
all:
  children:
    wazuh_agent_targets:
      hosts:
        monitor-01:
          ansible_host: 192.168.73.2
          ansible_user: ansible
        docker-network:
          ansible_host: 192.168.85.2
          ansible_user: ansible
        docker-blue:
          ansible_host: 192.168.40.39
          ansible_user: ansible
        alpha-prod-01:
          ansible_host: 192.168.80.118
          ansible_user: ansible
        kasm-01:
          ansible_host: 192.168.78.10
          ansible_user: ansible
        media-01:
          ansible_host: 192.168.40.42
          ansible_user: ansible
        ansible-01:
          ansible_host: 192.168.40.36
          ansible_user: ansible
          ansible_connection: local
        game-01:
          ansible_host: 192.168.80.30
          ansible_user: ansible
        grey-server:
          ansible_host: 192.168.70.10
          ansible_user: root
          wazuh_agent_groups: default,proxmox
        purple-server:
          ansible_host: 192.168.70.11
          ansible_user: root
          wazuh_agent_groups: default,proxmox
        blue-server:
          ansible_host: 192.168.70.12
          ansible_user: root
          wazuh_agent_groups: default,proxmox
        red-server:
          ansible_host: 192.168.70.13
          ansible_user: root
          wazuh_agent_groups: default,proxmox
        green-server:
          ansible_host: 192.168.70.14
          ansible_user: root
          wazuh_agent_groups: default,proxmox
        db-13-dev:
          ansible_host: 192.168.40.135
          ansible_user: ai-agent
          wazuh_agent_groups: default,workstation
