---
- hosts: lxc,management
  become: yes
  tasks:
    - name: Deploy authorized SSH keys
      authorized_key:
        user: root
        key: "{{ item }}"
        state: present
      loop:
        - "ssh-ed25519 <REDACTED_PUBLIC_KEY> jedi-pc"
        - "ssh-ed25519 <REDACTED_PUBLIC_KEY> mac-air3-<YOUR_ADMIN_USERNAME>"
        - "ssh-ed25519 <REDACTED_PUBLIC_KEY> ansible-control"

- hosts: VM
  become: no
  tasks:
    - name: Deploy authorized SSH keys
      authorized_key:
        user: <YOUR_ADMIN_USERNAME>
        key: "{{ item }}"
        state: present
      loop:
        - "ssh-ed25519 <REDACTED_PUBLIC_KEY> jedi-pc"
        - "ssh-ed25519 <REDACTED_PUBLIC_KEY> mac-air3-<YOUR_ADMIN_USERNAME>"
        - "ssh-ed25519 <REDACTED_PUBLIC_KEY> ansible-control"
