#!/usr/bin/env python3
"""Assert every PromQL expression in a Grafana dashboard returns data.

A dashboard can load cleanly and still show empty panels, which is worse than a
broken one because it reads as "nothing wrong". This walks the versioned
dashboard JSON, substitutes the Grafana variables the queries use, runs each
expression against the Prometheus HTTP API, and fails on any that error or come
back with no series.

Usage:
    python3 assert_dashboard_queries.py <dashboard.json|directory> [prometheus_base_url]

A directory is walked recursively, so one run covers every dashboard in
Configuration/grafana/dashboards/.

Default base URL is http://127.0.0.1:9090.

Exit codes:
    0  every query returned at least one series
    2  one or more queries returned an error
    3  one or more queries returned no series
    4  the dashboard file could not be read or parsed

Queries whose panel title appears in ALLOW_EMPTY may legitimately return
nothing; they are reported but do not fail the run. That list is generated by
Tools/build_dashboards.py into allow-empty.json beside this script, so a panel
built to be empty when healthy registers itself and nobody has to remember to
add it here.
"""

from __future__ import annotations

import json
import pathlib
import sys
import urllib.error
import urllib.parse
import urllib.request

# Grafana interpolates these before sending a query. The substitutions below
# mirror what the dashboard's own defaults resolve to, so the assertion tests
# the same expression Grafana would send.
# `$host` resolves to `.*` here rather than to one hostname, so the per-host
# detail row is tested against every host at once. Every panel there matches with
# `host=~"$host"` for exactly that reason.
VARIABLE_SUBSTITUTIONS = {
    "$__rate_interval": "5m",
    "$__interval": "1m",
    "$__range": "6h",
    "$role": ".*",
    "$host": ".*",
    "$service": ".*",
    "$ups": ".*",
    "$server": ".*",
    "$dockerhost": ".*",
    "$container": ".*",
}

# Panels that are correct when empty. A restart table with no rows means nothing
# restarted, which is the desired state rather than a fault.
def _load_allow_empty() -> set[str]:
    """Titles of panels that are correct when they return nothing.

    Generated beside this script by the dashboard builder. The literal below is
    the fallback for a copy of this script uploaded to a host on its own.
    """
    path = pathlib.Path(__file__).with_name("allow-empty.json")
    try:
        return set(json.loads(path.read_text(encoding="utf-8")))
    except Exception:
        return {"Container restarts in the last 6 hours"}


ALLOW_EMPTY = _load_allow_empty()


def interpolate(expr: str) -> str:
    for name, value in VARIABLE_SUBSTITUTIONS.items():
        expr = expr.replace(name, value)
    return expr


def collect_queries(dashboard: dict) -> list[tuple[str, str, str]]:
    """Return (panel_title, refId, expr) for every query, including nested rows."""
    found: list[tuple[str, str, str]] = []

    def walk(panels: list) -> None:
        for panel in panels or []:
            title = panel.get("title", "<untitled>")
            for target in panel.get("targets") or []:
                expr = target.get("expr")
                if expr and not target.get("hide"):
                    found.append((title, target.get("refId", "?"), expr))
            # Collapsed rows carry their children in a nested list.
            if panel.get("panels"):
                walk(panel["panels"])

    walk(dashboard.get("panels", []))
    return found


def run_query(base_url: str, expr: str) -> tuple[bool, int, str]:
    """Return (ok, series_count, message)."""
    url = f"{base_url.rstrip('/')}/api/v1/query?query=" + urllib.parse.quote(expr)
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            payload = json.load(response)
    except urllib.error.HTTPError as error:
        detail = ""
        try:
            detail = json.load(error).get("error", "")
        except Exception:
            detail = error.reason if hasattr(error, "reason") else str(error)
        return False, 0, f"HTTP {error.code}: {detail}"
    except Exception as error:  # noqa: BLE001 - report whatever the transport gave us
        return False, 0, str(error)

    if payload.get("status") != "success":
        return False, 0, payload.get("error", "query returned a non-success status")
    return True, len(payload["data"]["result"]), ""


def check_dashboard(path: str, base_url: str) -> tuple[int, int, int, int]:
    """Return (queries, errored, empty, allowed_empty) for one dashboard."""
    try:
        dashboard = json.load(open(path, encoding="utf-8"))
    except Exception as error:  # noqa: BLE001
        print(f"cannot read dashboard {path}: {error}")
        return (0, 1, 0, 0)

    queries = collect_queries(dashboard)
    title = dashboard.get("title", path)
    if not queries:
        print(f"  {title}: no queries found")
        return (0, 1, 0, 0)

    errored: list[str] = []
    empty: list[str] = []
    allowed_empty: list[str] = []

    for panel_title, ref_id, raw_expr in queries:
        expr = interpolate(raw_expr)
        ok, count, message = run_query(base_url, expr)
        label = f"{panel_title} [{ref_id}]"
        if not ok:
            print(f"  ERROR  {title} / {label}: {message}")
            errored.append(label)
        elif count == 0:
            if panel_title in ALLOW_EMPTY:
                allowed_empty.append(label)
            else:
                print(f"  EMPTY  {title} / {label}")
                empty.append(label)

    flag = "FAIL" if (errored or empty) else "ok  "
    print(f"  {flag}  {title}: {len(queries)} queries, "
          f"{len(allowed_empty)} allowed empty, {len(empty)} empty, {len(errored)} errored")
    return (len(queries), len(errored), len(empty), len(allowed_empty))


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 4

    target = pathlib.Path(argv[1])
    base_url = argv[2] if len(argv) > 2 else "http://127.0.0.1:9090"

    if target.is_dir():
        paths = sorted(target.rglob("*.json"))
        if not paths:
            print(f"no dashboards under {target}")
            return 4
    elif target.exists():
        paths = [target]
    else:
        print(f"no such path: {target}")
        return 4

    print(f"Checking {len(paths)} dashboard(s) against {base_url}\n")

    totals = [0, 0, 0, 0]
    for path in paths:
        result = check_dashboard(str(path), base_url)
        totals = [a + b for a, b in zip(totals, result)]

    queries, errored, empty, allowed_empty = totals
    print()
    print(f"{len(paths)} dashboards, {queries} queries: "
          f"{queries - errored - empty - allowed_empty} returned data, "
          f"{allowed_empty} allowed empty, {empty} unexpectedly empty, {errored} errored")

    if errored:
        return 2
    if empty:
        return 3
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
