logging {
  debug: off
  to_syslog: yes
}

nodelist {
  node {
    name: blue-server
    nodeid: 3
    quorum_votes: 1
    ring0_addr: 192.168.70.12
    ring1_addr: 192.168.71.12
  }
  node {
    name: grey-server
    nodeid: 1
    quorum_votes: 1
    ring0_addr: 192.168.70.10
    ring1_addr: 192.168.71.10
  }
  node {
    name: purple-server
    nodeid: 2
    quorum_votes: 1
    ring0_addr: 192.168.70.11
    ring1_addr: 192.168.71.11
  }
  node {
    name: red-server
    nodeid: 4
    quorum_votes: 1
    ring0_addr: 192.168.70.13
    ring1_addr: 192.168.71.13
  }
}

quorum {
  provider: corosync_votequorum
}

totem {
  cluster_name: Galaxy
  config_version: 8
  interface {
    linknumber: 0
  }
  interface {
    linknumber: 1
  }
  ip_version: ipv4-6
  link_mode: passive
  secauth: on
  version: 2
}

